"""empty message

Revision ID: 1a479d379ae5
Revises: 3570da67eb96
Create Date: 2021-01-20 14:06:56.399948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a479d379ae5'
down_revision = '3570da67eb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
